#!/usr/bin/env python3
"""ihx2c.py IHX BASE OUT.c SYMBOL -- embed an Intel HEX image as a C array.

The image runs from BASE to the highest address in the file; gaps are zero.
"""
import sys


def main() -> None:
    if len(sys.argv) != 5:
        sys.exit(f"usage: {sys.argv[0]} input.ihx base output.c symbol")
    ihx, base, out, sym = sys.argv[1], int(sys.argv[2], 0), sys.argv[3], sys.argv[4]
    mem = {}
    with open(ihx) as f:
        for line in f:
            line = line.strip()
            if not line.startswith(":"):
                continue
            n, addr, kind = int(line[1:3], 16), int(line[3:7], 16), int(line[7:9], 16)
            if kind == 1:
                break
            if kind != 0:
                continue
            for i in range(n):
                mem[addr + i] = int(line[9 + 2 * i : 11 + 2 * i], 16)
    if not mem or min(mem) < base:
        sys.exit(f"{ihx}: image empty or below {base:#06x}")
    data = bytes(mem.get(a, 0) for a in range(base, max(mem) + 1))
    with open(out, "w") as f:
        f.write(f"/* Generated by tools/ihx2c.py from {ihx}; do not edit. */\n")
        f.write("#include <stdint.h>\n")
        f.write(f"const uint8_t {sym}[] = {{\n")
        for i in range(0, len(data), 12):
            f.write("    " + ", ".join(f"0x{b:02x}" for b in data[i : i + 12]) + ",\n")
        f.write("};\n")
        f.write(f"const uint16_t {sym}_len = {len(data)};\n")


if __name__ == "__main__":
    main()
