; Default SIO channel B console backend.
;
; The backend keeps pluggable driver state and foreground-safe RX/TX buffers.
; The boot path enables the maskable SIO interrupt receiver after CP/M runtime
; bank setup is stable.

	.globl sio_console_driver,sio_console_init,sio_console_isr
	.globl CONIRQ,sio_console_enable_interrupts,sio_console_disable_interrupts
	.globl CONSOLE_DRIVER_CODE_START,CONSOLE_DRIVER_CODE_END
	.globl CONSOLE_IM2_VECTOR_ENTRY
	.globl CONSOLE_IM2_VECTOR_TABLE_START,CONSOLE_IM2_VECTOR_TABLE_END
	.globl CONSOLE_RX_HEAD,CONSOLE_RX_TAIL,CONSOLE_RX_COUNT
	.globl CONSOLE_TX_HEAD,CONSOLE_TX_TAIL,CONSOLE_TX_COUNT
	.globl CONSOLE_TX_ACTIVE,CONSOLE_IRQ_ENABLED
	.globl CONSOLE_IRQ_COUNT
	.globl CONSOLE_RX_BUFFER,CONSOLE_TX_BUFFER

CONSOLE_DATA_PORT	= SIOB_DATA
CONSOLE_CTRL_PORT	= SIOB_CTRL
CONSOLE_MASTER_CTRL_PORT	= SIOA_CTRL
CONSOLE_RX_READY	= RR0_RX_AVAILABLE
CONSOLE_TX_READY	= RR0_TX_EMPTY
CONSOLE_EOF		= 0x1a
CONSOLE_READY		= 0xff
CONSOLE_RX_BUFFER_SIZE	= 0x10
CONSOLE_TX_BUFFER_SIZE	= 0x10
CONSOLE_RX_BUFFER_MASK	= CONSOLE_RX_BUFFER_SIZE - 1
CONSOLE_TX_BUFFER_MASK	= CONSOLE_TX_BUFFER_SIZE - 1

	.area CODE (ABS)
	.org CBIOS_IM2_VECTOR_TABLE

CONSOLE_IM2_VECTOR_TABLE_START:
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE,CBIOS_IM2_VECTOR_BYTE
	.db CBIOS_IM2_VECTOR_BYTE
CONSOLE_IM2_VECTOR_TABLE_END:

	.area CODE (ABS)
	.org CBIOS_CONSOLE_DRIVER_CODE_BASE

CONSOLE_DRIVER_CODE_START:

sio_console_driver:
	.dw sio_console_const
	.dw sio_console_conin
	.dw sio_console_conout
	.dw sio_console_list
	.dw sio_console_punch
	.dw sio_console_reader
	.dw sio_console_listst

; Initialize the SIO-backed console driver state. Boot enables interrupts after
; the current bank and CP/M page-zero vectors are in place.
; Clobbers: AF, HL.
sio_console_init:
	xor a
	ld (CONSOLE_RX_HEAD),a
	ld (CONSOLE_RX_TAIL),a
	ld (CONSOLE_RX_COUNT),a
	ld (CONSOLE_TX_HEAD),a
	ld (CONSOLE_TX_TAIL),a
	ld (CONSOLE_TX_COUNT),a
	ld (CONSOLE_TX_ACTIVE),a

	call sio_console_disable_interrupts
	ret

CONIRQ:
	or a
	jp z,sio_console_disable_interrupts

sio_console_enable_interrupts:
	di
	ld a,#CBIOS_IM2_VECTOR_PAGE
	ld i,a
	im 2

	ld a,#0x02
	out (CONSOLE_CTRL_PORT),a
	ld a,#CBIOS_SIO_VECTOR
	out (CONSOLE_CTRL_PORT),a

	ld a,#SIO_WR0_RESET_HIGHEST_IUS
	out (CONSOLE_CTRL_PORT),a
	ld a,#0x01
	out (CONSOLE_CTRL_PORT),a
	ld a,#SIO_WR1_RX_INT_ALL
	out (CONSOLE_CTRL_PORT),a
	ld a,#0x09
	out (CONSOLE_MASTER_CTRL_PORT),a
	ld a,#SIO_WR9_MIE
	out (CONSOLE_MASTER_CTRL_PORT),a
	xor a
	ld (CONSOLE_IRQ_COUNT),a
	ld (CONSOLE_IRQ_COUNT + 1),a
	ld a,#0x01
	ld (CONSOLE_IRQ_ENABLED),a
	ei
	ld a,#0xff
	ret

; Returns A = 0xff when buffered input is available, A = 0x00 otherwise.
sio_console_const:
	call sio_console_rx_kick
	ld a,(CONSOLE_RX_COUNT)
	or a
	jr z,SIO_CONSOLE_CONST_NONE
	ld a,#CONST_HAS_CHAR
	ret
SIO_CONSOLE_CONST_NONE:
	ld a,#CONST_NO_CHAR
	ret

; Blocks on the interrupt-filled receive buffer, not on SIO status polling.
sio_console_conin:
	push de
	push hl
SIO_CONSOLE_CONIN_WAIT:
	call sio_console_rx_kick
	ld a,(CONSOLE_RX_COUNT)
	or a
	jr nz,SIO_CONSOLE_CONIN_HAVE_CHAR
	jr SIO_CONSOLE_CONIN_WAIT
SIO_CONSOLE_CONIN_HAVE_CHAR:
	call sio_console_rx_lock
	ld hl,#CONSOLE_RX_BUFFER
	ld a,(CONSOLE_RX_TAIL)
	ld e,a
	ld d,#0x00
	add hl,de
	ld a,(hl)
	push af
	ld a,(CONSOLE_RX_TAIL)
	inc a
	and #CONSOLE_RX_BUFFER_MASK
	ld (CONSOLE_RX_TAIL),a
	ld a,(CONSOLE_RX_COUNT)
	dec a
	ld (CONSOLE_RX_COUNT),a
	call sio_console_rx_unlock
	pop af
	pop hl
	pop de
	ret

; Blocks until transmit is ready, then writes C exactly as supplied.
sio_console_conout:
	push af
SIO_CONSOLE_CONOUT_WAIT:
	in a,(CONSOLE_CTRL_PORT)
	and #CONSOLE_TX_READY
	jr z,SIO_CONSOLE_CONOUT_WAIT
	ld a,c
	out (CONSOLE_DATA_PORT),a
	pop af
	ret

sio_console_list:
	ret

sio_console_punch:
	ret

sio_console_reader:
	ld a,#CONSOLE_EOF
	ret

sio_console_listst:
	ld a,#CONSOLE_READY
	ret

sio_console_isr:
	push af
	push bc
	push de
	push hl

	ld hl,(CONSOLE_IRQ_COUNT)
	inc hl
	ld (CONSOLE_IRQ_COUNT),hl

	in a,(CONSOLE_CTRL_PORT)
	ld b,a
	and #CONSOLE_RX_READY
	jr z,SIO_ISR_CHECK_TX
	in a,(CONSOLE_DATA_PORT)
	ld c,a
	call sio_console_rx_store

SIO_ISR_CHECK_TX:
	ld a,b
	and #CONSOLE_TX_READY
	jr z,SIO_ISR_DONE
	call sio_console_tx_drain

SIO_ISR_DONE:
	ld a,#SIO_WR0_RESET_HIGHEST_IUS
	out (CONSOLE_CTRL_PORT),a
	pop hl
	pop de
	pop bc
	pop af
	reti

; Input: C = received byte. Drops the new byte when the buffer is full.
sio_console_rx_store:
	ld a,(CONSOLE_RX_COUNT)
	cp #CONSOLE_RX_BUFFER_SIZE
	ret nc
	ld hl,#CONSOLE_RX_BUFFER
	ld a,(CONSOLE_RX_HEAD)
	ld e,a
	ld d,#0x00
	add hl,de
	ld (hl),c
	ld a,(CONSOLE_RX_HEAD)
	inc a
	and #CONSOLE_RX_BUFFER_MASK
	ld (CONSOLE_RX_HEAD),a
	ld a,(CONSOLE_RX_COUNT)
	inc a
	ld (CONSOLE_RX_COUNT),a
	ret

sio_console_rx_kick:
	call sio_console_rx_lock
	in a,(CONSOLE_CTRL_PORT)
	and #CONSOLE_RX_READY
	jr z,SIO_CONSOLE_RX_KICK_DONE
	push bc
	push hl
	in a,(CONSOLE_DATA_PORT)
	ld c,a
	call sio_console_rx_store
	pop hl
	pop bc
SIO_CONSOLE_RX_KICK_DONE:
	call sio_console_rx_unlock
	ret

sio_console_rx_lock:
	ld a,(CONSOLE_IRQ_ENABLED)
	or a
	ret z
	di
	ret

sio_console_rx_unlock:
	ld a,(CONSOLE_IRQ_ENABLED)
	or a
	ret z
	ei
	ret

sio_console_tx_drain:
	ld a,(CONSOLE_TX_COUNT)
	or a
	jr z,SIO_ISR_TX_IDLE
	ld hl,#CONSOLE_TX_BUFFER
	ld a,(CONSOLE_TX_TAIL)
	ld e,a
	ld d,#0x00
	add hl,de
	ld a,(hl)
	out (CONSOLE_DATA_PORT),a
	ld a,(CONSOLE_TX_TAIL)
	inc a
	and #CONSOLE_TX_BUFFER_MASK
	ld (CONSOLE_TX_TAIL),a
	ld a,(CONSOLE_TX_COUNT)
	dec a
	ld (CONSOLE_TX_COUNT),a
	ret

SIO_ISR_TX_IDLE:
	xor a
	ld (CONSOLE_TX_ACTIVE),a
	ret

sio_console_tx_kick:
	in a,(CONSOLE_CTRL_PORT)
	and #CONSOLE_TX_READY
	ret z
	jp sio_console_tx_drain

sio_console_disable_interrupts:
	di
	ld a,#0x01
	out (CONSOLE_CTRL_PORT),a
	xor a
	out (CONSOLE_CTRL_PORT),a
	ld a,#0x09
	out (CONSOLE_MASTER_CTRL_PORT),a
	xor a
	out (CONSOLE_MASTER_CTRL_PORT),a
	ld (CONSOLE_TX_ACTIVE),a
	ld (CONSOLE_IRQ_ENABLED),a
	ret

	.area CODE (ABS)
	.org CBIOS_IM2_VECTOR_ENTRY
CONSOLE_IM2_VECTOR_ENTRY:
	jp sio_console_isr

CONSOLE_DRIVER_CODE_END:

	.area WORK (ABS)
	.org CBIOS_CONSOLE_DRIVER_WORK_AREA
CONSOLE_DRIVER_STATE_START:
CONSOLE_RX_HEAD:
	.db 0x00
CONSOLE_RX_TAIL:
	.db 0x00
CONSOLE_RX_COUNT:
	.db 0x00
CONSOLE_TX_HEAD:
	.db 0x00
CONSOLE_TX_TAIL:
	.db 0x00
CONSOLE_TX_COUNT:
	.db 0x00
CONSOLE_TX_ACTIVE:
	.db 0x00
CONSOLE_IRQ_ENABLED:
	.db 0x00
CONSOLE_IRQ_COUNT:
	.dw 0x0000
CONSOLE_RX_BUFFER:
	.ds CONSOLE_RX_BUFFER_SIZE
CONSOLE_TX_BUFFER:
	.ds CONSOLE_TX_BUFFER_SIZE
CONSOLE_DRIVER_STATE_END:

	.area CODE (ABS)
