#!/usr/bin/env python3
"""Generate BDOSCHAR's deterministic on-machine fixture table.

The generated include contains metadata, not prebuilt CP/M files.  BDOSCHAR's
SETUP mode consumes it and creates the files through the running BDOS so USER
selection, zero-length MAKE/CLOSE, sequential record counts, and function 30
attribute changes exercise the same ZSDOS boundary being characterized.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


ATTR_RO = 0x01
ATTR_SYS = 0x02
ATTR_ARC = 0x04


@dataclass(frozen=True)
class Fixture:
    user: int
    name: str
    records: int
    attrs: int = 0

    def __post_init__(self) -> None:
        if not 0 <= self.user <= 15:
            raise ValueError(f"ZSDOS USER must be 0 through 15: {self.user}")
        if not 0 <= self.records <= 0xFFFF:
            raise ValueError(f"record count does not fit the fixture table: {self.records}")
        if self.attrs & ~(ATTR_RO | ATTR_SYS | ATTR_ARC):
            raise ValueError(f"unsupported attribute flags: {self.attrs:#x}")

    def packed_name(self) -> str:
        stem, suffix = self.name.split(".")
        if not (1 <= len(stem) <= 8 and len(suffix) <= 3):
            raise ValueError(f"not an 8.3 name: {self.name}")
        packed = stem.upper().ljust(8) + suffix.upper().ljust(3)
        if any(not (c.isalnum() or c in "_ ") for c in packed):
            raise ValueError(f"unsupported CP/M character in {self.name}")
        return packed


FIXTURES = [
    Fixture(0, "BDEXACT.DAT", 1),
    *(Fixture(0, f"BDWILD{n:02d}.DAT", n) for n in range(1, 6)),
    Fixture(0, "BDEMPTY.DAT", 0),
    *(Fixture(0, f"BR{records:06d}.DAT", records)
      for records in (1, 2, 3, 4, 127, 128, 129, 255, 256, 257)),
    Fixture(0, "BAATTRR.DAT", 1, ATTR_RO),
    Fixture(0, "BAATTRS.DAT", 1, ATTR_SYS),
    Fixture(0, "BAATTRA.DAT", 1, ATTR_ARC),
    Fixture(0, "BAATTRX.DAT", 1, ATTR_RO | ATTR_SYS | ATTR_ARC),
    *(Fixture(user, "BUCOMMON.DAT", 1) for user in (0, 1, 15)),
]


def asm_ascii(value: str) -> str:
    return value.replace('"', '""')


def render() -> str:
    lines = [
        "; Generated by tools/generate_bdoschar_fixtures.py. Do not edit.",
        "; Entry: USER, attribute flags, record count LE, packed 8.3 name.",
        "; Sentinel USER FFh ends the table.",
        "",
        f"BDOSCHAR_FIXTURE_COUNT = {len(FIXTURES)}",
        "BDOSCHAR_ATTR_RO        = 0x01",
        "BDOSCHAR_ATTR_SYS       = 0x02",
        "BDOSCHAR_ATTR_ARC       = 0x04",
        "",
        "bdoschar_fixture_table:",
    ]
    for fixture in FIXTURES:
        lines.extend([
            f"\t; USER {fixture.user:02d}, {fixture.name}, "
            f"{fixture.records} record(s), attributes {fixture.attrs:02X}h",
            f"\t.db 0x{fixture.user:02x},0x{fixture.attrs:02x}",
            f"\t.dw 0x{fixture.records:04x}",
            f'\t.ascii "{asm_ascii(fixture.packed_name())}"',
        ])
    lines.extend(["\t.db 0xff", ""])
    return "\n".join(lines)


def render_submit(program_drive: str, fixture_drive: str, output_drive: str) -> bytes:
    p = program_drive.upper()
    f = fixture_drive.upper()
    o = output_drive.upper()
    lines = [
        f"{p}:BDOSCHAR {f}:SETUP",
        f"{p}:BDOSCHAR BDEXACT.DAT {o}:BCDEF.TXT",
        f"{p}:BDOSCHAR {f}:BDEXACT.DAT {o}:BCEXP.TXT",
        f"{p}:BDOSCHAR {f}:BDWILD??.DAT {o}:BCWILD.TXT",
        f"{p}:BDOSCHAR {f}:BDEMPTY.DAT {o}:BCEMPTY.TXT",
        f"{p}:BDOSCHAR {f}:BR??????.DAT {o}:BCRECORD.TXT",
        f"{p}:BDOSCHAR {f}:BAATTR?.DAT {o}:BCATTR.TXT",
        "USER 0",
        f"{p}:BDOSCHAR {f}:BUCOMMON.DAT {o}:BCU00.TXT",
        "USER 1",
        f"{p}:BDOSCHAR {f}:BUCOMMON.DAT {o}:BCU01.TXT",
        "USER 15",
        f"{p}:BDOSCHAR {f}:BUCOMMON.DAT {o}:BCU15.TXT",
        "USER 0",
    ]
    return ("\r\n".join(lines) + "\r\n").encode("ascii") + b"\x1a"


def parse_drive(value: str) -> str:
    value = value.upper()
    if len(value) != 1 or not ("A" <= value <= "P"):
        raise argparse.ArgumentTypeError("drive must be one letter A-P")
    return value


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("src/bdoschar_fixtures.inc"),
        help="generated ASxxxx include (default: %(default)s)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the existing output differs instead of rewriting it",
    )
    parser.add_argument(
        "--submit-output",
        type=Path,
        default=Path("src/bdoschar.sub"),
        help="generated CP/M SUBMIT file (default: %(default)s)",
    )
    parser.add_argument("--program-drive", type=parse_drive, default="B")
    parser.add_argument("--fixture-drive", type=parse_drive, default="B")
    parser.add_argument("--output-drive", type=parse_drive, default="C")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    rendered = render()
    submit = render_submit(args.program_drive, args.fixture_drive, args.output_drive)
    if args.check:
        existing = args.output.read_text() if args.output.exists() else ""
        if existing != rendered:
            raise SystemExit(f"stale generated fixture table: {args.output}")
        existing_submit = args.submit_output.read_bytes() if args.submit_output.exists() else b""
        if existing_submit != submit:
            raise SystemExit(f"stale generated command file: {args.submit_output}")
        print(f"bdoschar fixtures: OK ({len(FIXTURES)} files)")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    args.submit_output.parent.mkdir(parents=True, exist_ok=True)
    args.submit_output.write_bytes(submit)
    print(f"wrote {args.output} and {args.submit_output} ({len(FIXTURES)} files)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
