#!/usr/bin/env python3
"""Emit the common-memory addresses ZSDOS jumps to, as a CP/M MACLIB.

ZSDOS is assembled separately from the BIOS, so it cannot resolve BIOS symbols
the way the stock BDOS could -- that one was linked alongside them.  The
addresses therefore have to be handed to it, and they cannot be hardcoded: they
move whenever the BIOS is rebuilt, and a stale address would assemble cleanly
and jump into the middle of something at run time.

WBTRAP is the warm-boot trap ZSDOS's exits jump to instead of RST 0.  ZSDOS runs
in bank 7, in latch mode 11, and the trap restores mode 10 before jumping to
0000h (banked OS plan, F1).

The asxxxx map truncates symbol names to eight characters, so the lookup
matches on that prefix and fails loudly if it is ambiguous.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

WANTED = {
    "WBTRAP": ("wbtrap", "wbtrap"),
}


def find(symbols: str, prefix: str, full: str) -> int:
    hits = set(re.findall(rf"\b{re.escape(prefix)}\w*\s+([0-9A-Fa-f]{{8}})", symbols))
    if not hits:
        raise SystemExit(f"symbol {full} ({prefix}) not found in the map")
    if len(hits) > 1:
        raise SystemExit(f"symbol prefix {prefix} is ambiguous: {sorted(hits)}")
    return int(hits.pop(), 16)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--symbols", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    symbols = args.symbols.read_text(errors="replace")
    lines = [
        "; Generated by tools/gen_zsdos_bios.py -- do not edit.",
        "; Common-memory addresses ZSDOS jumps to, taken from the firmware symbol map.",
        "",
    ]
    for name, (prefix, full) in WANTED.items():
        addr = find(symbols, prefix, full)
        lines.append(f"{name}\tEQU\t0{addr:04X}H\t; {full}")
        print(f"  {name} = {addr:04X}h  ({full})")
    args.output.write_bytes(("\r\n".join(lines) + "\r\n").encode("ascii"))


if __name__ == "__main__":
    main()
