#!/usr/bin/env python3
"""Emit the resident addresses the ROM service page calls back into.

The service page is assembled separately from the firmware and executes from
ROM, so it cannot resolve firmware symbols.  It does not need many -- the
console lives at E000h-ECADh, which is common RAM and stays mapped while a
service runs, so a migrated routine can keep calling what it left behind -- but
every one of those addresses moves whenever the BIOS is rebuilt.  Writing them
down would produce a page that assembles cleanly and jumps into the middle of
something at run time, which is the failure gen_zsdos_bios.py exists to prevent
on the ZSDOS side.

Unlike that tool this reads the LISTING rather than the map.  The asxxxx map
truncates symbol names to eight characters, and the console's names collide
there: v9958_write_vram_small, v9958_write_register and
v9958_write_register_block all reduce to "v9958_wr".  The listing carries full
names.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Labels: "    0000EA74 ...  nnn v9958_write_vram_small:"
LABEL = re.compile(
    r"^\s{4}([0-9A-F]{8})(?: [0-9A-F]{2})*\s*(?:\[\s*\d+\])?\s+\d+\s?\t?\s*"
    r"([A-Za-z_][A-Za-z0-9_]*):"
)
# Equates: "                    0000E000   443 NAME     = 0xe000"
EQUATE = re.compile(
    r"^\s+([0-9A-F]{8})\s+\d+\s+([A-Za-z_][A-Za-z0-9_]*)\s*=" 
)


def collect(listing: Path) -> dict[str, list[int]]:
    found: dict[str, list[int]] = {}
    for line in listing.read_text(errors="replace").splitlines():
        m = LABEL.match(line) or EQUATE.match(line)
        if not m:
            continue
        found.setdefault(m.group(2), []).append(int(m.group(1), 16))
    return found


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--listing", type=Path, required=True)
    ap.add_argument("--output", type=Path, required=True)
    ap.add_argument("--symbol", action="append", default=[],
                    help="symbol the ROM service page needs; repeatable")
    args = ap.parse_args()

    if not args.listing.is_file():
        raise SystemExit(f"gen_romsvc_bios: missing listing {args.listing}")

    found = collect(args.listing)

    missing = [s for s in args.symbol if s not in found]
    if missing:
        raise SystemExit(
            "gen_romsvc_bios: not in the listing: " + ", ".join(missing)
            + "\n  The ROM service page calls these; a missing one means the "
              "firmware no longer defines it, and the page must be updated "
              "rather than pointed at a stale address."
        )

    # A label defined at two addresses is an alias or a duplicated name; either
    # way the page cannot be told which one it meant.
    ambiguous = [s for s in args.symbol if len(set(found[s])) > 1]
    if ambiguous:
        raise SystemExit(
            "gen_romsvc_bios: defined at more than one address: "
            + ", ".join(ambiguous)
        )

    lines = [
        "; Generated by tools/gen_romsvc_bios.py -- do not edit.",
        "; Resident addresses the ROM service page calls back into.",
        f"; Source: {args.listing}",
        "",
    ]
    width = max((len(s) for s in args.symbol), default=1)
    for name in args.symbol:
        lines.append(f"{('RES_' + name):<{width + 4}} = 0x{found[name][0]:04x}")
    lines.append("")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines))
    print(f"gen_romsvc_bios: {len(args.symbol)} symbols -> {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
