#!/usr/bin/env python3
"""Emit the BIOS helper addresses ZSDOS calls, as a CP/M MACLIB.

ZSDOS is assembled separately from the BIOS, so it cannot resolve BIOS symbols
the way the stock BDOS could -- that one was linked alongside them.  The
addresses therefore have to be handed to it, and they cannot be hardcoded:
ccp_clear_redraw lives in the core BIOS and ccp_read_up_sequence in a driver
slot, so both move whenever the BIOS is rebuilt.  A stale address here would
assemble cleanly and jump into the middle of something at run time.

The asxxxx map truncates symbol names to eight characters, so the lookup
matches on that prefix and fails loudly if it is ambiguous.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

WANTED = {
    "CCPCLR": ("ccp_clea", "ccp_clear_redraw"),
    "CCPUP":  ("ccp_read", "ccp_read_up_sequence"),
}


def find(symbols: str, prefix: str, full: str) -> int:
    hits = set(re.findall(rf"\b{re.escape(prefix)}\w*\s+([0-9A-Fa-f]{{8}})", symbols))
    if not hits:
        raise SystemExit(f"symbol {full} ({prefix}) not found in the map")
    if len(hits) > 1:
        raise SystemExit(f"symbol prefix {prefix} is ambiguous: {sorted(hits)}")
    return int(hits.pop(), 16)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--symbols", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    symbols = args.symbols.read_text(errors="replace")
    lines = [
        "; Generated by tools/gen_zsdos_bios.py -- do not edit.",
        "; BIOS entry points ZSDOS calls, taken from the firmware symbol map.",
        "",
    ]
    for name, (prefix, full) in WANTED.items():
        addr = find(symbols, prefix, full)
        lines.append(f"{name}\tEQU\t0{addr:04X}H\t; {full}")
        print(f"  {name} = {addr:04X}h  ({full})")

    # The CCP slot's page range, for CCPBUF's "is a command processor asking?"
    # test.  ZSDOS carried 0C4H and 0CCH inline, which were the MEM=56 answers
    # and became wrong the moment the resident base moved -- the test then said
    # "somebody else" for every CCP call, and empty-line ^R recall silently
    # stopped working.  A range test should ask where the CCP actually is.
    cbase = find(symbols, "CBASE", "CP/M CCP base")
    lines.append("")
    lines.append(f"CCPLO\tEQU\t0{cbase >> 8:02X}H\t; CCP slot, first page")
    lines.append(f"CCPHI\tEQU\t0{(cbase + 0x800) >> 8:02X}H\t; first page at or above the BDOS")
    print(f"  CCPLO = {cbase >> 8:02X}h, CCPHI = {(cbase + 0x800) >> 8:02X}h  (CCP slot pages)")
    args.output.write_bytes(("\r\n".join(lines) + "\r\n").encode("ascii"))


if __name__ == "__main__":
    main()
